# Generated by Django 4.2.7 on 2025-07-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_businessowner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptoken',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Subscription duration in days (optional)', null=True),
        ),
    ]
