# Generated by Django 4.2.7 on 2025-08-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
